# arch: arm64-graviton2
# virt: lxd
# os: linux
# dist: focal
language: java
cache:
  directories:
  - "$HOME/.cache"

install:
- git clone https://${GITHUB_TOKEN}@github.com/javaf/deploy "$HOME/deploy"
- cp "$HOME/deploy/settings.xml" "$HOME/.m2/settings.xml"
- gpg --import "$HOME/deploy/private.key"
- gpg --import "$HOME/deploy/public.key"
- cp "$HOME/deploy/.ssh"/* "$HOME/.ssh/"
- chmod 400 "$HOME/.ssh/id_rsa"

script:
- export MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
- mvn $MAVEN_OPTS -B deploy
- mvn $MAVEN_OPTS -B deploy -Dossrh
