# arch: arm64-graviton2
# virt: lxd
os: linux
dist: focal
language: java
cache:
  directories:
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libxml2-utils

before_install:
- git clone https://${GITHUB_TOKEN}@github.com/javaf/deploy "$HOME/deploy"
- cp "$HOME/deploy/settings.xml" "$HOME/.m2/settings.xml"
- gpg --import "$HOME/deploy/private.key"
- gpg --import "$HOME/deploy/public.key"
- cp "$HOME/deploy/.ssh"/* "$HOME/.ssh/"
- chmod 400 "$HOME/.ssh/id_rsa"

# skip duplicate install
# maven already does it
install:
- 'true'

deploy:
  provider: script
  script: "mvn --batch-mode --no-transfer-progress deploy"
  cleanup: false
  on:
    branch: main
